//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Famvin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FamVinEntities : DbContext
    {
        public FamVinEntities()
            : base("name=FamVinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<Council> Council { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Occupation> Occupation { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Region> Region { get; set; }
    }
}
